name: Publish ProShape to Maven Central

on:
  workflow_dispatch: # ou `push: tags: [v*.*.*]` pour tag-based

jobs:
  publish:
    name: Publish library
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish to Maven Central
        run: ./gradlew publish --no-daemon --stacktrace